### ISSUE TITLE
New about

### ISSUE THREAD

**Issue by suvozit** [RimeOfficial/about#1]
@girishnayak12 I have added @tripathi-ankit (RW access) as a contributor to this repo

**Comment by girishnayak12** [comment]
# Team
```
We are merely explorers of infinity,
in the pursuit of absolute perfection.
&mdash; [The Man Who Knew Infinity Official Trailer #1 (2016)](https://youtu.be/oXGm9Vlfx4w?t=2m10s)
```

**Comment by suvozit** [comment]
instagram.com
about/us
about/jobs
about/faq
about/legal/terms
about/legal/terms/api
about/legal/privacy
about/legal/libraries

google.com
intl/en/about
intl/en/about/products
intl/en/about/company
intl/en/about/company/facts
intl/en/about/company/facts/culture
intl/en/about/company/facts/locations
intl/en/about/company/philosophy
intl/en/about/company/products
intl/en/services
intl/en/press
intl/en/press/images.html
intl/en/press/blog-social-directory.html
policies
policies/privacy
policies/terms
policies/technologies
policies/faq

about.twitter.com
company
company/press
company/press/milestones
company/press/leadership
company/press/photos
company/blogs
company/policy
company/brand
careers
